### ISSUE TITLE
Compress on JS and decompress on Arduino

### ISSUE THREAD

**Issue by capedra** [siara-cc/Unishox2#28]
Hello, whenever I do a simple compress of a string on Node.JS using Unishox-JS library and I decode it on C++ (Arduino), it shows strange characters and simply don't work. Has anyone tested it before? Could someone please help me? Thanks!

**Comment by siara-cc** [comment]
Hi @capedra, Thank you for trying it out.  The Javascript library and this would be interoperable only if input is passed as Uint8Array and another Uint8Array is passed for output.  This is because when passing Javascript strings, the letter locations for repeating sequences are not the same as a Utf-8 array.

**Comment by siara-cc** [comment]
See https://github.com/siara-cc/Unishox_JS#interoperability-with-the-c-library
