### ISSUE TITLE
Benchmark against Snappy

### ISSUE THREAD

**Issue by Dan-Do** [siara-cc/Unishox2#33]
I am coming from Crystal-lang. I want to experiment this awesome library, so I create a C-binding for it.
The snappy code is written natively in crystal, here is the link https://github.com/naqvis/snappy
The input is Vietnamese text encoded in UTF-8 which size is 1008 bytes.

Here is the benchmark result.
```shell
Compression benchmark
unishox 880.16  (  1.14ms) (± 9.10%)   1.0kB/op  52.39× slower
 snappy  46.11k ( 21.69µs) (± 8.79%)  4.04kB/op        fastest

Decompression benchmark
unishox  28.76k ( 34.77µs) (± 8.71%)  1.0kB/op   4.46× slower
 snappy 128.24k (  7.80µs) (± 7.62%)  1.0kB/op        fastest

snappy: in_size = 1008, out_size = 774, ratio = 76.78571428571429
unishox: in_size = 1008, out_size = 624, ratio = 61.904761904761905
```
The speed is reasonale because the compression ration is good. Though, I wonder if we can make it faster :)

**Comment by Dan-Do** [comment]
I got exeption for this text
`@&@&!/-!?,().,@"@@&€¥$%#{{[><~\\'bcxhj+¥$$ mmay`
where the output size is 67 bytes which is greater than input size of 51 bytes.

Is this expected? How can we avoid that?

**Comment by siara-cc** [comment]
Hi, Thanks for your interest. Snappy is a general purpose algorithm designed to be fast.  Unishox is designed for compressing only short text content and since it employs different strategies for better compression I am afraid it will be slower.

The given string compresses and decompresses correctly:

```sh
./test_unishox2 "@&@&\!/-\!?,().,@\"@@&€¥$%#{{[><~\\'bcxhj+¥\$\$ mmay"
```

but expands in size because of using mostly special characters.  This is expected and to avoid exception it would be necessary to provide an output size of more than 67 bytes.

**Comment by Dan-Do** [comment]
I got it. Thank you.

**Comment by Dan-Do** [comment]
By the way, can we gain more speed if we move the calculation to GPU, e.g CUDA?

**Comment by siara-cc** [comment]
Theoretically yes.  At first the algorithm needs to find out which compression method to use and the GPU is ideal for parallelising this.  There are so many changes I would like to make to improve the speed as well as compression ratio, but just waiting to see how useful or how many people use this so I can put in more effort in it.
However thanks for the suggestion.  That is a great idea!!
