### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by gbaraldi** [siara-cc/Unishox2#37]
Hi, I'm the author https://github.com/gbaraldi/Unishox.jl, a julia wrapper of unishox.
Is the NUL character an allowed value in the middle of a compressed string? 
I say that because in a pathological string I got one, and since julia normally expects a C style NUL terminated string when getting a string from a pointer I got a bug. Thanks for the cool library anyway :).

**Comment by PallHaraldsson** [comment]
I think you may have misunderstood. Or did I? It seems you added a test only, for the input string. It should of course be allowed to be null-terminated. Or even include null everywhere else, but problem @gbaraldi asked for was for null in the middle of a compressed string. I doubt you can or should do anything about that. Nor should need to. It's to be expected in compressed information. I guess you could try to avoid it, slowing down the compressor at least, but I think you shouldn't and your users should just expect them. You might however want to document that... I'm not sure why this should be a problem on the Julia side. Julia already allows for null in the middle of a String (the type), while it does have a CString for C compatibility that's null-terminated, for compatibility with C, and basically the problem is with C not Julia. I guess for this you should avoid using CString, rather use a Vector of UInt8.

**Comment by gbaraldi** [comment]
It's not a problem, which is why I posed the issue this way, it's just that I expected a string coming from C to be a C style NUL terminated string. Since I expected that, I told julia to do that to, which meant if it found a NUL in the middle of the string it would think it ended there. So I guess it's just an issue of documentation more than an actual bug.

**Comment by siara-cc** [comment]
I guess I don't understand the issue, but just wanted to mention that the implementation unishox2.c does not expect the input to be a valid UTF-8 string or a null terminated string.  It assumes it to be a series of bytes of given length and there should be no issue reproducing the original input after decompression even if it has nulls in between or at the end.
Now if the input is text, then we get good ratios and otherwise may not.
